import {
    NAV_ITEM_TYPE_TITLE,
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'

import type { NavigationTree } from '@/types/navigation'

const getAdminNavigationConfig = (prefix: string): NavigationTree[] => [
    {
        key: 'admin.dashboard',
        path: `/${prefix}/dashboard`,
        title: 'Dashboard',
        translateKey: 'nav.admin.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['admin'],
        subMenu: [],
    },
    {
        key: 'admin.users',
        path: `/${prefix}/users`,
        title: 'Users',
        translateKey: 'nav.admin.users',
        icon: 'users',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['admin'],
        subMenu: [],
    },
    {
        key: 'admin.subscriptions',
        path: `/${prefix}/subscriptions`,
        title: 'Subscriptions',
        translateKey: 'nav.admin.subscriptions',
        icon: 'subscription',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['admin'],
        subMenu: [],
    },
    {
        key: 'admin.orders',
        path: `/${prefix}/orders`,
        title: 'Orders',
        translateKey: 'nav.admin.orders',
        icon: 'order',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['admin'],
        subMenu: [],
    },
    {
        key: 'admin.cms',
        path: '',
        title: 'CMS',
        translateKey: 'nav.admin.cms',
        icon: 'cms',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['admin'],
        subMenu: [
            {
                key: 'admin.cms.pages',
                path: `/${prefix}/pages`,
                title: 'Info Pages',
                translateKey: 'nav.admin.cms.pages',
                icon: 'pages',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.cms.blog',
                path: `/${prefix}/blog`,
                title: 'Blog',
                translateKey: 'nav.admin.cms.blog',
                icon: 'blog',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'admin.settings',
        path: '',
        title: 'Settings',
        translateKey: 'nav.admin.settings',
        icon: 'settings',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['admin'],
        subMenu: [
            {
                key: 'admin.settings.appearance',
                path: `/${prefix}/settings/appearance`,
                title: 'Appearance',
                translateKey: 'nav.admin.settings.appearance',
                icon: 'appearance',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
            {
                key: 'admin.settings.admins',
                path: `/${prefix}/settings/admins`,
                title: 'Admins',
                translateKey: 'nav.admin.settings.admins',
                icon: 'admins',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['admin'],
                subMenu: [],
            },
        ],
    },
];

const userNavigationConfig: NavigationTree[] = [
    {
        key: 'user.dashboard',
        path: '/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.user.dashboard',
        icon: 'dashboard',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['user'],
        subMenu: [],
    },
    {
        key: 'user.clients',
        path: '/clients',
        title: 'Clients',
        translateKey: 'nav.user.clients',
        icon: 'users',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['user'],
        subMenu: [],
    },
     {
        key: 'user.projects',
        path: '',
        title: 'Projects',
        translateKey: 'nav.user.projects',
        icon: 'project',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['user'],
        subMenu: [
            {
                key: 'user.projects.list',
                path: '/projects',
                title: 'List View',
                translateKey: 'nav.user.projects.list',
                icon: 'list',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
            {
                key: 'user.projects.kanban',
                path: '/projects/kanban',
                title: 'Kanban',
                translateKey: 'nav.user.projects.kanban',
                icon: 'kanban',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
            {
                key: 'user.time-tracking',
                path: '/time-tracking',
                title: 'Time Tracking',
                translateKey: 'nav.user.time-tracking',
                icon: 'clock',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
        ],
    },
    {
        key: 'user.tasks',
        path: '/tasks',
        title: 'Tasks',
        translateKey: 'nav.user.tasks',
        icon: 'task',
        type: NAV_ITEM_TYPE_ITEM,
        authority: ['user'],
        subMenu: [],
    },
     {
        key: 'user.settings',
        path: '',
        title: 'Settings',
        translateKey: 'nav.user.settings',
        icon: 'settings',
        type: NAV_ITEM_TYPE_TITLE,
        authority: ['user'],
        subMenu: [
            {
                key: 'user.settings.appearance',
                path: `/appearance`,
                title: 'Appearance',
                translateKey: 'nav.admin.settings.appearance',
                icon: 'appearance',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
            {
                key: 'user.settings.members',
                path: `/settings/members`,
                title: 'Members',
                translateKey: 'nav.user.settings.members',
                icon: 'users',
                type: NAV_ITEM_TYPE_ITEM,
                authority: ['user'],
                subMenu: [],
            },
        ],
    },
]

export { getAdminNavigationConfig, userNavigationConfig }

export default userNavigationConfig
